spring.application.name=photo-archive
spring.datasource.url=jdbc:postgresql://localhost:5432/photo_archive_db
spring.datasource.username=practice_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


